export const data = {
  letter: [
    { key: "q" },
    { key: "w" },
    { key: "e" },
    { key: "r" },
    { key: "t" },
    { key: "y" },
    { key: "u" },
    { key: "i" },
    { key: "o" },
    { key: "p" },
    { key: "a" },
    { key: "s" },
    { key: "d" },
    { key: "f" },
    { key: "g" },
    { key: "h" },
    { key: "j" },
    { key: "k" },
    { key: "l" },
    { key: "Enter" },
    { key: "z" },
    { key: "x" },
    { key: "c" },
    { key: "v" },
    { key: "b" },
    { key: "n" },
    { key: "m" },
    { key: "Backspace" },
  ],
  solutions: [
    { word: "grasp", id: 1 },
    { word: "flint", id: 2 },
    { word: "crisp", id: 3 },
    { word: "jumpy", id: 4 },
    { word: "vapor", id: 5 },
    { word: "blush", id: 6 },
    { word: "knock", id: 7 },
    { word: "swirl", id: 8 },
    { word: "motel", id: 9 },
    { word: "punch", id: 10 },
    { word: "zebra", id: 11 },
    { word: "shiny", id: 12 },
    { word: "tiger", id: 13 },
    { word: "quake", id: 14 },
    { word: "frost", id: 15 },
    { word: "latch", id: 16 },
    { word: "hover", id: 17 },
    { word: "dizzy", id: 18 },
    { word: "trick", id: 19 },
    { word: "waltz", id: 20 },
    { word: "spike", id: 21 },
    { word: "fable", id: 22 },
    { word: "grind", id: 23 },
    { word: "lunar", id: 24 },
    { word: "brave", id: 25 },
    { word: "sling", id: 26 },
    { word: "charm", id: 27 },
    { word: "pluck", id: 28 },
    { word: "sheep", id: 29 },
    { word: "wrath", id: 30 },
    { word: "bloom", id: 31 },
    { word: "grain", id: 32 },
    { word: "flick", id: 33 },
    { word: "smirk", id: 34 },
    { word: "creek", id: 35 },
    { word: "gloom", id: 36 },
    { word: "thorn", id: 37 },
    { word: "brick", id: 38 },
    { word: "spear", id: 39 },
    { word: "vivid", id: 40 },
    { word: "piano", id: 41 },
    { word: "crane", id: 42 },
    { word: "tempo", id: 43 },
    { word: "swoop", id: 44 },
    { word: "foamy", id: 45 },
    { word: "nerdy", id: 46 },
    { word: "tramp", id: 47 },
    { word: "dwell", id: 48 },
    { word: "scent", id: 49 },
    { word: "kneel", id: 50 },
    { word: "ninja", id: 51 },
    { word: "spade", id: 52 },
    { word: "pools", id: 53 },
    { word: "drive", id: 54 },
    { word: "relax", id: 55 },
    { word: "times", id: 56 },
    { word: "train", id: 57 },
    { word: "cores", id: 58 },
    { word: "pours", id: 59 },
    { word: "blame", id: 60 },
    { word: "banks", id: 61 },
    { word: "phone", id: 62 },
    { word: "bling", id: 63 },
    { word: "coins", id: 64 },
    { word: "hello", id: 65 },
    { word: "apple", id: 66 },
    { word: "beach", id: 67 },
    { word: "chose", id: 68 },
    { word: "diary", id: 69 },
    { word: "ember", id: 60 },
    { word: "glide", id: 61 },
    { word: "quest", id: 62 },
  ],
};
